apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-microservices
  annotations:
    # This annotation ensures Projects (Namespaces) are created first when deployed via Argo CD
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-microservices
  namespace: kargo-microservices
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
