# Values for the dev stage (namespace online-boutique-dev).
# Tags below are written by Kargo (yaml-update step) on promotion.
image:
  tags:
    adservice: v0.10.5
    cartservice: v0.10.5
    checkoutservice: v0.10.5
    currencyservice: v0.10.5
    emailservice: v0.10.5
    frontend: v0.10.5
    loadgenerator: v0.10.5
    paymentservice: v0.10.5
    productcatalogservice: v0.10.5
    recommendationservice: v0.10.5
    shippingservice: v0.10.5
