{{- $s := include "online-boutique.service" . | fromYaml }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $s.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
